import fs from 'fs';

const creators = {
  "Interstellar": "Christopher Nolan",
  "Oppenheimer": "Christopher Nolan",
  "Parasite": "Bong Joon-ho",
  "Dune: Part Two": "Denis Villeneuve",
  "The Dark Knight": "Christopher Nolan",
  "Avengers: Endgame": "Anthony and Joe Russo",
  "Everything Everywhere All at Once": "Daniel Kwan, Daniel Scheinert",
  "Inside Out 2": "Kelsey Mann",
  "Deadpool & Wolverine": "Shawn Levy",
  "Gladiator II": "Ridley Scott",
  "Avatar: The Way of Water": "James Cameron",
  "Top Gun: Maverick": "Joseph Kosinski",
  "The Batman": "Matt Reeves",
  "Spider-Man: Across the Spider-Verse": "Joaquim Dos Santos",
  "Barbie": "Greta Gerwig",
  "John Wick: Chapter 4": "Chad Stahelski",
  "Mad Max: Fury Road": "George Miller",
  "Inception": "Christopher Nolan",
  "Joker": "Todd Phillips",
  "Dune": "Denis Villeneuve",
  "Mission: Impossible 8": "Christopher McQuarrie",
  "Mickey 17": "Bong Joon-ho",
  "Avatar: Fire and Ash": "James Cameron",
  "The Batman - Part II": "Matt Reeves",
  "Avengers: Secret Wars": "Russo Brothers",
  "The Lord of the Rings: The Return of the King": "Peter Jackson",
  "Pulp Fiction": "Quentin Tarantino",
  "Forrest Gump": "Robert Zemeckis",
  "Madame Web": "S.J. Clarkson",
  "Morbius": "Daniel Espinosa",
  "Cats": "Tom Hooper",
  "The Room": "Tommy Wiseau",
  "Green Lantern": "Martin Campbell",
  "The Flash": "Andy Muschietti",
  "Attack on Titan": "Hajime Isayama / WIT / MAPPA",
  "Fullmetal Alchemist: B": "Hiromu Arakawa / Bones",
  "Demon Slayer": "Koyoharu Gotouge / Ufotable",
  "Jujutsu Kaisen": "Gege Akutami / MAPPA",
  "One Piece": "Eiichiro Oda / Toei",
  "Spy x Family": "Tatsuya Endo / WIT / CloverWorks",
  "Chainsaw Man": "Tatsuki Fujimoto / MAPPA",
  "Vinland Saga": "Makoto Yukimura / WIT / MAPPA",
  "Blue Lock": "Muneyuki Kaneshiro / Eight Bit",
  "Solo Leveling": "Chugong / A-1 Pictures",
  "Frieren": "Kanehito Yamada / Madhouse",
  "Death Note": "Tsugumi Ohba / Madhouse",
  "Hunter x Hunter": "Yoshihiro Togashi / Madhouse",
  "Naruto: Shippuden": "Masashi Kishimoto / Pierrot",
  "My Hero Academia": "Kohei Horikoshi / Bones",
  "Steins;Gate": "Chiyomaru Shikura / White Fox",
  "Mob Psycho 100": "ONE / Bones",
  "One Punch Man": "ONE / Madhouse",
  "Cyberpunk: Edgerunners": "Trigger",
  "Cowboy Bebop": "Shinichiro Watanabe / Sunrise",
  "Sakamoto Days": "Yuto Suzuki",
  "Dandadan": "Yukinobu Tatsu / Science SARU",
  "One Punch Man Season 3": "ONE / J.C.Staff",
  "Jujutsu Kaisen Season 3": "Gege Akutami / MAPPA",
  "Demon Slayer: Infinity Castle": "Koyoharu Gotouge / Ufotable",
  "Code Geass": "Sunrise",
  "Neon Genesis Evangelion": "Hideaki Anno / Gainax",
  "Your Name": "Makoto Shinkai / CoMix Wave Films",
  "Ex-Arm": "Visual Flight",
  "Pupa": "Studio Deen",
  "School Days": "TNK",
  "Sword Art Online": "Reki Kawahara / A-1 Pictures",
  "Crash Landing on You": "Park Ji-eun / Lee Jung-hyo",
  "Squid Game": "Hwang Dong-hyuk",
  "Squid Game Season 2": "Hwang Dong-hyuk",
  "My Mister": "Park Hae-young / Kim Won-seok",
  "It's Okay to Not Be Okay": "Jo Yong / Park Shin-woo",
  "Vincenzo": "Park Jae-bum / Kim Hee-won",
  "Extraordinary Attorney Woo": "Moon Ji-won / Yoo In-shik",
  "Goblin": "Kim Eun-sook / Lee Eung-bok",
  "Queen of Tears": "Park Ji-eun / Jang Young-woo",
  "Lovely Runner": "Lee Si-eun / Yoon Jong-ho",
  "Reply 1988": "Lee Woo-jung / Shin Won-ho",
  "The Glory": "Kim Eun-sook / Ahn Gil-ho",
  "Business Proposal": "Han Seol-hee / Park Seon-ho",
  "Twenty-Five Twenty-One": "Kwon Do-eun / Jung Ji-hyun",
  "Mr. Sunshine": "Kim Eun-sook / Lee Eung-bok",
  "Hospital Playlist": "Lee Woo-jung / Shin Won-ho",
  "Signal": "Kim Eun-hee / Kim Won-seok",
  "Descendants of the Sun": "Kim Eun-sook / Lee Eung-bok",
  "Itaewon Class": "Kwang Jin / Kim Sung-yoon",
  "Moving": "Kang Full / Park In-je",
  "When the Stars Gossip": "Seo Sook-hyang / Park Shin-woo",
  "Jeju Odyssey": "Unknown",
  "All of Us Are Dead Season 2": "Chun Sung-il / Lee Jae-kyoo",
  "Squid Game Season 3": "Hwang Dong-hyuk",
  "Gyeongseong Creature Season 2": "Kang Eun-kyung / Chung Dong-yoon",
  "My Name": "Kim Ba-da / Kim Jin-min",
  "Crash Course in Romance": "Yang Hee-seung / Yoo Je-won",
  "Bloodhounds": "Kim Joo-hwan",
  "Blood": "Park Jae-bum / Ki Min-soo",
  "Melting Me Softly": "Baek Mi-kyung / Shin Woo-chul",
  "The Bride of Habaek": "Jung Yoon-jung / Kim Byung-soo",
  "Breaking Bad": "Vince Gilligan",
  "Stranger Things": "The Duffer Brothers",
  "Game of Thrones": "David Benioff, D.B. Weiss",
  "The Last of Us": "Craig Mazin, Neil Druckmann",
  "House of the Dragon": "Ryan Condal, George R. R. Martin",
  "Wednesday": "Alfred Gough, Miles Millar",
  "The Bear": "Christopher Storer",
  "Shōgun": "Rachel Kondo, Justin Marks",
  "Severance": "Dan Erickson",
  "The White Lotus": "Mike White",
  "Dark": "Baran bo Odar, Jantje Friese",
  "Peaky Blinders": "Steven Knight",
  "Ozark": "Bill Dubuque, Mark Williams",
  "Better Call Saul": "Vince Gilligan, Peter Gould",
  "Black Mirror": "Charlie Brooker",
  "Succession": "Jesse Armstrong",
  "The Boys": "Eric Kripke",
  "Chernobyl": "Craig Mazin",
  "True Detective": "Nic Pizzolatto",
  "Fargo": "Noah Hawley",
  "Daredevil: Born Again": "Dario Scardapane",
  "The Mandalorian S4": "Jon Favreau",
  "Stranger Things Season 5": "The Duffer Brothers",
  "The Last of Us Season 2": "Craig Mazin, Neil Druckmann",
  "Euphoria Season 3": "Sam Levinson",
  "The Wire": "David Simon",
  "The Sopranos": "David Chase",
  "Band of Brothers": "Tom Hanks, Steven Spielberg",
  "The Idol": "Sam Levinson",
  "Velma": "Charlie Grandy",
  "Inhumans": "Scott Buck",
  "Emily in Paris": "Darren Star",
  "Atomic Habits": "James Clear",
  "The Alchemist": "Paulo Coelho",
  "Project Hail Mary": "Andy Weir",
  "Fourth Wing": "Rebecca Yarros",
  "Ikigai": "Héctor García, Francesc Miralles",
  "Educated": "Tara Westover",
  "The Midnight Library": "Matt Haig",
  "A Court of Thorns & Roses": "Sarah J. Maas",
  "It Ends with Us": "Colleen Hoover",
  "Intermezzo": "Sally Rooney",
  "Wind and Truth": "Brandon Sanderson",
  "1984": "George Orwell",
  "The Martian": "Andy Weir",
  "Sapiens": "Yuval Noah Harari",
  "Thinking, Fast and Slow": "Daniel Kahneman",
  "The Great Gatsby": "F. Scott Fitzgerald",
  "To Kill a Mockingbird": "Harper Lee",
  "Pride and Prejudice": "Jane Austen",
  "The Hobbit": "J.R.R. Tolkien",
  "Onyx Storm": "Rebecca Yarros",
  "The Winds of Winter": "George R. R. Martin",
  "The Doors of Stone": "Patrick Rothfuss",
  "Alecto the Ninth": "Tamsyn Muir",
  "Stormlight Archive 6": "Brandon Sanderson",
  "The Tortured Poets Dept.": "Taylor Swift",
  "Cowboy Carter": "Beyoncé",
  "GNX": "Kendrick Lamar",
  "Short n' Sweet": "Sabrina Carpenter",
  "GUTS": "Olivia Rodrigo",
  "SOS": "SZA",
  "Midnights": "Taylor Swift",
  "Renaissance": "Beyoncé",
  "Harry's House": "Harry Styles",
  "Hit Me Hard and Soft": "Billie Eilish",
  "Brat": "Charli XCX",
  "1989 (Taylor's Version)": "Taylor Swift",
  "Chromatica": "Lady Gaga",
  "Future Nostalgia": "Dua Lipa",
  "After Hours": "The Weeknd",
  "Folklore": "Taylor Swift",
  "Astroworld": "Travis Scott",
  "Igor": "Tyler, The Creator",
  "Blonde": "Frank Ocean",
  "To Pimp a Butterfly": "Kendrick Lamar",
  "Reputation (Taylor's Version)": "Taylor Swift",
  "Lasso": "Lana Del Rey",
  "LG7 (Lady Gaga)": "Lady Gaga",
  "Act III (Beyoncé)": "Beyoncé",
  "New Blackpink Album": "Blackpink",
  "Thriller": "Michael Jackson",
  "The Dark Side of the Moon": "Pink Floyd",
  "Abbey Road": "The Beatles"
};

let content = fs.readFileSync('./src/data/content.js', 'utf8');

for (const [title, creator] of Object.entries(creators)) {
  const safeTitle = title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`("title":\\s*"${safeTitle}",[\\s\\S]*?"desc":\\s*")([^"]+)(")`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3) => {
    if (p2.includes(`By ${creator}`) || p2.includes(`by ${creator}`)) {
      return match;
    }
    return `${p1}By ${creator}. ${p2}${p3}`;
  });
}

fs.writeFileSync('./src/data/content.js', content, 'utf8');
console.log('Enriched all descriptions with creators!');
